### ISSUE TITLE
Gi feilmelding hvis produsering av dokument feiler

### ISSUE THREAD

**Issue by maccyber** [telemark/tfk-saksbehandling-elev-varsel#10]
Nå produseres det en pdf som f.eks. kan ha innholdet;

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

Feiler først mot SvarUt.

**Comment by zrrrzzt** [comment]
Tror løsningen her er å bruke samme variant som vi gjør på MinElev.

Der får man enten en pdf eller ikke fordi alt foregår på samme server.
